---
title: "cleanscores"
author: "Alina Skripets"
date: "November 16, 2017"
output: github_document
---
# Imaginary Stats 133 class grades

## What is the data about?
It is somewhat limited statistics on the NBA players.

## How many rows?
334 + 1 title row
## How many columns?
23
## What are the column labels?
HW1	HW2	HW3	HW4	HW5	HW6	HW7	HW8	HW9	ATT	QZ1	QZ2	QZ3	QZ4	EX1	EX2 Test1	Test2	Homework	Quiz	Overall	Lab	Grade
    
# If the column names are abbreviations, what is the full description of each column?
• HW1, HW2,	HW3,	HW4,	HW5,	HW6,	HW7,	HW8,	HW9: grades of homeworks, one of which can be dropped
• ATT: attendance, number of attended labs
• QZ1	QZ2	QZ3	QZ4: quiz grades
• EX1	EX2: grades on the first and second exam
• Test1	Test2: rescaled 0 to 100 EX1 and EX2
• Homework	Quiz Lab: rescaled average of hwks and quizes, lowest score dropped
• Overall: Overall numeric grade for the course according to appropriate weights
• Grade: Letter grade according to the table of scores

# What are the units of measurement (e.g. inches, pounds, km/h, etc)?
• HW1, HW2,	HW3,	HW4,	HW5,	HW6,	HW7,	HW8,	HW9: numeric - points, 100 points max, one hw dropped
• ATT: numeric - number ranges from 0 to 12
• QZ1	QZ2	QZ3	QZ4: numeric - points out of 12, out of 18, out of 20, out of 20, accordingly
• EX1	EX2:numeric - points on the exam out of 80 and out of 90 accordingly
• Test1	Test2: numeric, 0 to 100 
• Homework	Quiz Lab: numeric, 0 to 100
• Overall: numeric, 0 to 100
• Grade: character

# How missing values are codified?
Missing values are replaced with 0
